package br.ufmg.ppgee.orcslab.upmsp.neighborhood;

import br.ufmg.ppgee.orcslab.upmsp.problem.Problem;
import br.ufmg.ppgee.orcslab.upmsp.problem.Solution;

import java.util.Random;

/**
 * Common interface implemented by all neighborhoods.
 */
public interface Neighborhood {

    /**
     * Return the name of the movement that defines the neighborhood.
     * @return The name of the movement that defines the neighborhood.
     */
    String getName();

    /**
     * Return the best neighbor.
     * @param problem The instance of the problem.
     * @param solution Start solution from which the neighborhood will be generated.
     * @return The best neighbor of the start solution.
     */
    Solution getBestNeighbor(Problem problem, Solution solution);

    /**
     * Returns any neighbor solution.
     * @param problem The instance of the problem.
     * @param solution Start solution from which the neighborhood will be generated.
     * @param random A random number generator.
     * @return Any neighbor solution of the start solution.
     */
    Solution getAnyNeighbor(Problem problem, Solution solution, Random random);

    /**
     * Return some statistics about a neighborhood.
     * @param problem The instance of the problem.
     * @param solution Start solution from which the neighborhood will be generated.
     * @return Some statistics about the neighborhood generated by the start solution.
     */
    Stats getStats(Problem problem, Solution solution);

}
